import os
from ..format import *
class Editor:
    def __init__(self, file, lang):
        self.file = file
        self.lang = lang

    def exits(self):
        return os.path.exists(self.filepath())

    def filepath(self):
        return os.path.join(os.path.dirname(__file__), self.file)
    def content(self):
        if self.exits():
            with open(os.path.join(os.path.dirname(__file__), self.file), "r") as file:
                content = file.read()
                return content
        else:
            return None
    def write(self, content):
        with open(os.path.join(os.path.dirname(__file__), self.file), "w") as file:
            file.write(content)
            return True

    def server(self, lang, content, file_path):
        from flask import Flask, render_template, request
        app = Flask(__name__)
        @app.route("/<file>")
        def home(file):
            return render_template("editor.html", lang=lang, content=content, file_path=file_path, file=file)

        @app.route('/write', methods=["POST"])
        def write():
            content = request.form.get("content")
            self.write(content)
            return f"<h1 style='font-family: consolas, monospace; font-size: 84px; text-align: center;'>🐍 SNAKE RUN <br><br> Saved file {self.file}!</h1>"

        import webbrowser
        webbrowser.open(f'http://localhost:5000/{self.file}')
        app.run(debug=False)

    def open(self):
        if self.exits():
            self.server(self.lang, self.content(), self.filepath())
        else:
            print(self.filepath())
            c_print(f"File {self.file} doesn't exist", code="danger")
            make_response = ask(f"Do you want to create {self.file}?")
            if make_response:
                with open(os.path.join(os.path.dirname(__file__), self.file), "w") as file:
                    file.write("This is boiler plate code generated by the editor.")
                self.server(self.lang, self.content(), self.filepath())
            else:
                pass
            return False


class Md:
    def __init__(self, name):
        self.name = name
    def up(self):
        from flask import render_template, Flask, request
        app = Flask(__name__)
        def read(filename):
            try:
                file = open(filename, 'r')
                file_contents = file.read()
                file.close()
                return file_contents
            except:
                file = open(filename, 'w')
                file.write(
                    "# This is a boiler plate code generated by snakerun\nStart Typing Below")
                return "# This is a boiler plate code generated by snakerun\n#Start Typing Below"

        @app.route('/', methods=['GET'])
        def home():
            return "<h1 style='font-family: consolas, monospace; font-size: 84px; text-align: center;'>🐍 SNAKE RUN <br><br> There is nothing to see here!</h1>"

        @app.route('/save', methods=['POST'])
        def save():
            name = request.form.get('name')
            content = request.form.get('text')
            with open(name, 'w') as file:
                file.write(content)
                return f"<h1 style='font-family: consolas, monospace; font-size: 84px; text-align: center;'>🐍 SNAKE RUN <br><br> Saved file {self.name}!</h1>"

        @app.route(f'/{self.name}', methods=['GET', 'POST'])
        def main():
            import os
            return render_template('md.html', filename=self.name, filename_adv=f'{os.getcwd()}/{self.name}',
                                   content=read(f'{os.getcwd()}/{self.name}'))

        import webbrowser
        webbrowser.open(f'http://localhost:5000/{self.name}')
        app.run(debug=False)